version: "3.8"

services:
  mysql:
    container_name: chat_app_mysql
    image: mysql:8.0
    command: --init-file /chat_app/data/init.sql
    volumes:
        - ./data/init.sql:/chat_app/data/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=CHAT_APP
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

  phpmyadmin:
    container_name: chat_app_phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - 8888:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - "mysql"
      
  mongo:
    container_name: chat_app_mongo
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /chat_app/data:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: chat_app_redis
    image: redis:7.0

  server:
    container_name: chat_app_server
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/chat_app
      - /chat_app/node_modules
    ports:
      - "5500:5500"
    command: "npm run dev"
    depends_on:
      - "mysql"
      - "mongo"